# Database Configuration (prod)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# CORS Configuration (prod)
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

# Logging Configuration (prod)
logging.level.com.main.app=INFO
logging.level.org.mybatis.spring=INFO
logging.level.org.springframework.web=INFO

# 운영에서는 SQL stdout 출력 비활성화
mybatis.configuration.log-impl=org.apache.ibatis.logging.nologging.NoLoggingImpl
